/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SitrepRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "owner" | "registrar" | "verificar"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ManifiestoRegistrado"): EventFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registrar",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificar",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registrar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verificar", data: BytesLike): Result;
}

export namespace ManifiestoRegistradoEvent {
  export type InputTuple = [hash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [hash: string, timestamp: bigint];
  export interface OutputObject {
    hash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SitrepRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SitrepRegistry;
  waitForDeployment(): Promise<this>;

  interface: SitrepRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;

  registrar: TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;

  verificar: TypedContractMethod<
    [hash: BytesLike],
    [[boolean, bigint] & { exists: boolean; timestamp: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registrar"
  ): TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificar"
  ): TypedContractMethod<
    [hash: BytesLike],
    [[boolean, bigint] & { exists: boolean; timestamp: bigint }],
    "view"
  >;

  getEvent(
    key: "ManifiestoRegistrado"
  ): TypedContractEvent<
    ManifiestoRegistradoEvent.InputTuple,
    ManifiestoRegistradoEvent.OutputTuple,
    ManifiestoRegistradoEvent.OutputObject
  >;

  filters: {
    "ManifiestoRegistrado(bytes32,uint256)": TypedContractEvent<
      ManifiestoRegistradoEvent.InputTuple,
      ManifiestoRegistradoEvent.OutputTuple,
      ManifiestoRegistradoEvent.OutputObject
    >;
    ManifiestoRegistrado: TypedContractEvent<
      ManifiestoRegistradoEvent.InputTuple,
      ManifiestoRegistradoEvent.OutputTuple,
      ManifiestoRegistradoEvent.OutputObject
    >;
  };
}
